### ISSUE TITLE
error on the demo cardnet

### ISSUE THREAD

**Issue by hitspring2015** [S4WRXTTCS/jetson-inference#1]
Hello ，THANK YOU for your examples! I have compiled the codes successfully! But when I run the demo 

$ ./blackjack-camera 

and it occurs this error
 
blackjack-camera: cudnnEngine.cpp:486: bool nvinfer1::cudnn::Engine::deserialize(std::istream&): Assertion `input.good()' failed.
how can I resolve this problem ， need your help! thanks!

**Comment by S4WRXTTCS** [comment]
A few questions.

What type of system are you trying it on? I've only tested it on the Jetson TX1, and TX2

If it is the Jetson TX1/TX2 then what Jetpack version is it on?

Do the official jetson-inference examples work?  https://github.com/dusty-nv/jetson-inference

**Comment by hitspring2015** [comment]
thank for your reply! I run the example on the TX1，the system is ubuntu 16.04 and the Jetpack version is 2.3.1！ Also the  official jetson-inference examples can work ! when I compiled the codes of yours, and run 

$ ./detectnet-camera ped-100  

it can work.

but when I run
 
$ ./dualnet-camera

it occurs 

```
dualnet-camera:  successfully initialized video device
    width:  1280
   height:  720
    depth:  12 (bpp)

[GIE]  attempting to open cache file cardnet-100/snapshot_iter_10500.caffemodel.tensorcache
[GIE]  loading network profile from cache... cardnet-100/snapshot_iter_10500.caffemodel.tensorcache
[GIE]  platform has FP16 support.
[GIE]  cardnet-100/snapshot_iter_10500.caffemodel loaded
dualnet-camera: cudnnEngine.cpp:486: bool nvinfer1::cudnn::Engine::deserialize(std::istream&): Assertion `input.good()' failed.
Aborted
```

**Comment by hitspring2015** [comment]
Thank you very much for your examples! the problem maybe the cardnet-100 caffemodel. when I change the model which is about face detect  and compiling it again . and then run the command

$ ./dualnet-camera

it can work so cool! thank you for your example!
